esphome:
  name: luxpower_inverter
  platform: ESP32
  board: esp32dev

external_components:
  - source: github://your-repo/luxpower_sna/components

wifi:
  ssid: "your-ssid"
  password: "your-password"

logger:

switch:
  - platform: luxpower_ac_charge
    name: "AC Charge Enable"
  - platform: luxpower_forced_charge
    name: "Forced Charge"

number:
  - platform: luxpower_max_charge_current
    name: "Max Charge Current"
    min_value: 0
    max_value: 100
    step: 1
  - platform: luxpower_battery_soc
    name: "Battery SOC Target"
    min_value: 0
    max_value: 100
    step: 1

button:
  - platform: luxpower_system_restart
    name: "System Restart"
