substitutions:
# +--------------------------------------+
# name that will appear in esphome and homeassistant.
  name: luxpower
  
esphome:
  name: ${name}

# +--------------------------------------+
# | ESP32 settings                       |
# +--------------------------------------+
# For a stable Bluetooth connection keep the "esp-idf" framework
esp32:
  board: lolin_s2_mini

external_components:
# this one for remote firmware update but it only work on http
#  - source: github://pr#5586
#    components: [ http_request ]
  - source: github://paulsteigel/luxpower_sna@main
    refresh: 0s   

logger:
  level: DEBUG

#api:
#  reboot_timeout: 0s

# If you don't want to use ESPHome's native API you can use MQQT instead.
# In this case don't forget to remove the 'api:' section.
mqtt:
  broker: "your MQTT host address"
  username: "your MQTT user"
  password: "your password"
  client_id: ${name}_mqtt
  #keepalive: 
  #  seconds: 300

# In the event of problems with the WiFi network, the ESP32 will reboot every 15 minutes to try to resolve the problem.
# If we don't want to connect the ESP32 to the WiFi network please remove the 4 lines below.

wifi:
  ap:
    ssid: "ESP32S2Lolin"
#    password: "your passwword for the hotspot if no wifi station defined"
ota:
  - platform: esphome
    # safe_mode: false
    on_state_change:
      - logger.log: esphome.on_state_change
    port: 8266
    password: "your ota password"
  
captive_portal:

# define your packages if you want to separate different entities on different yaml
#packages:

#web_server:
#  port: 80
#  log: false
#  ota: false

# define the external component here
luxpower_sna:
  id: ${name}_luxpower_hub
  host: "your wifi dongle ip address"
  port: "8000"
  dongle_serial: "your wifi dongle serial"
  inverter_serial_number: "your inverter serial"
  update_interval: 20s

sensor:
# 3Define all the available numeric sensors
  - platform: luxpower_sna    
    luxpower_sna_id: ${name}_luxpower_hub
    pv1_voltage:
      name: "${name}_PV1 Voltage"
    pv2_voltage:
      name: "${name}_PV2 Voltage"
    battery_voltage:
      name: "${name}_Battery Voltage"
    soc:
      name: "${name}_Battery SOC"
    pv1_power:
      name: "${name}_PV1 Power"
    pv2_power:
      name: "${name}_PV2 Power"
    charge_power:
      name: "${name}_Battery Charge Power"
    discharge_power:
      name: "${name}_Battery Discharge Power"
    inverter_power:
      name: "${name}_Inverter Power"
    power_to_grid:
      name: "${name}_Power to Grid"
    power_from_grid:
      name: "${name}_Power from Grid"
    grid_voltage_r:
      name: "${name}_Grid Voltage R"
    grid_frequency:
      name: "Grid Frequency"
    #eps_active_power:
    #  name: "EPS Power"
    #bus1_voltage:
    #  name: "Bus1 Voltage"

    # --- Daily Energy Totals ---
    pv1_energy_today:
      name: "${name}_PV1 Energy Today"
    pv2_energy_today:
      name: "${name}_PV2 Energy Today"
    battery_current:
      name: "${name}_Battery Current"
    #battery_count:
    #  name: "Battery Count"
    battery_capacity:
      name: "${name}_Battery Capacity"
    max_cell_voltage:
      name: "${name}_Max Cell Voltage"
    min_cell_voltage:
      name: "${name}_Min Cell Voltage"
