substitutions:
# +--------------------------------------+
# name that will appear in esphome and homeassistant.
  name: luxpower
  
esphome:
  name: ${name}

# +--------------------------------------+
# | ESP32 settings                       |
# +--------------------------------------+
# For a stable Bluetooth connection keep the "esp-idf" framework
esp32:
  board: lolin_s2_mini

external_components:
# this one for remote firmware update but it only work on http
#  - source: github://pr#5586
#    components: [ http_request ]
  - source: github://paulsteigel/luxpower_sna@main
    refresh: 0s   

logger:
  level: DEBUG

# Please use the native `api` component instead of the `mqtt` section.
# If you use Home Assistant, the native API is more lightweight.
# If there is no HA server connected to this API, the ESP32 reboots every 15 minutes to try to resolve the problem.
# If you don't use Home Assistant please uncomment the "reboot_timeout: 0s" option.
#api:
#  reboot_timeout: 0s

# If you don't want to use ESPHome's native API you can use MQQT instead.
# In this case don't forget to remove the 'api:' section.
mqtt:
  broker: myhome.sfdp.net
  username: mqtt_user
  password: D1ndh1sk@
  client_id: ${name}_mqtt
  #keepalive: 
  #  seconds: 300

# In the event of problems with the WiFi network, the ESP32 will reboot every 15 minutes to try to resolve the problem.
# If we don't want to connect the ESP32 to the WiFi network please remove the 4 lines below.

wifi:
  ap:
    ssid: "ESP32S2Lolin"
#    password: !secret wifi_ap_password
ota:
  - platform: esphome
    # safe_mode: false
    on_state_change:
      - logger.log: esphome.on_state_change
    port: 8266
    password: "D1ndh1sk@"
  
captive_portal:

packages:
#  dyndns_pkg: !include ./commons/dyndns.yaml
  otahttp_pkg: !include ./commons/ota_http.yaml
  charge_discharge_pkg: !include ./commons/charge_discharge_control.yaml
  globals_pkg: !include ./commons/globals.yaml
  sensors_pkg: !include ./commons/text_sensors.yaml
  numbers_pkg: !include ./commons/numbers.yaml
  switchs_pkg: !include ./commons/switchs.yaml
  canbus_pkg: !include ./commons/canbus.yaml

#web_server:
#  port: 80
#  log: false
#  ota: false

output:
  - platform: gpio
    pin: 15
    id: led
    inverted: true

light:
  - platform: binary
    output: led
    id: blue_led
    name: "Blue LED"
    internal: true

# +--------------------------------------+
# | JK-BMS UART connection               |
# +--------------------------------------+

uart:
  id: uart_0
  baud_rate: 115200
  rx_buffer_size: 384
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

#  debug:
#    direction: BOTH

jk_modbus:
  id: modbus0
  uart_id: uart_0

jk_bms:
  id: bms0
  jk_modbus_id: modbus0
  # enable_fake_traffic: true

luxpower_sna:
  id: ${name}_luxpower_hub
  host: "192.168.100.10"
  port: 8000
  dongle_serial: "BA32500699"
  inverter_serial_number: "3253631886"
  update_interval: 20s

binary_sensor:
  - platform: jk_bms
    balancing:
      name: "${name} balancing"
    balancing_switch:
      name: "${name} balancing switch"
    charging:
      name: "${name} charging"
    charging_switch:
      id: charging_switch
      name: "${name} charging switch"
    discharging:
      name: "${name} discharging"
    discharging_switch:
      id: discharging_switch
      name: "${name} discharging switch"
    dedicated_charger_switch:
      name: "${name} dedicated charger switch"

sensor:
  - platform: jk_bms
    min_cell_voltage:
      id: min_cell_voltage
      name: "${name} min cell voltage"
    max_cell_voltage:
      id: max_cell_voltage
      name: "${name} max cell voltage"
    min_voltage_cell:
      id: min_voltage_cell
      name: "${name} min voltage cell"
    max_voltage_cell:
      id: max_voltage_cell
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    cell_voltage_9:
      name: "${name} cell voltage 9"
    cell_voltage_10:
      name: "${name} cell voltage 10"
    cell_voltage_11:
      name: "${name} cell voltage 11"
    cell_voltage_12:
      name: "${name} cell voltage 12"
    cell_voltage_13:
      name: "${name} cell voltage 13"
    cell_voltage_14:
      name: "${name} cell voltage 14"
    cell_voltage_15:
      name: "${name} cell voltage 15"
    cell_voltage_16:
      name: "${name} cell voltage 16"
#    cell_voltage_17:
#      name: "${name} cell voltage 17"
#    cell_voltage_18:
#      name: "${name} cell voltage 18"
#    cell_voltage_19:
#      name: "${name} cell voltage 19"
#    cell_voltage_20:
#      name: "${name} cell voltage 20"
#    cell_voltage_21:
#      name: "${name} cell voltage 21"
#    cell_voltage_22:
#      name: "${name} cell voltage 22"
#    cell_voltage_23:
#      name: "${name} cell voltage 23"
#    cell_voltage_24:
#      name: "${name} cell voltage 24"
    power_tube_temperature:
      id: power_tube_temperature
      name: "${name} power tube temperature"
    temperature_sensor_1:
      id: temperature_sensor_1
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      id: temperature_sensor_2
      name: "${name} temperature sensor 2"
    total_voltage:
      id: total_voltage
      name: "${name} total voltage"
    current:
      id: current
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    capacity_remaining:
      id: capacity_remaining
      name: "${name} capacity remaining"
    capacity_remaining_derived:
      id: capacity_remaining_derived
      name: "${name} capacity remaining derived"
    temperature_sensors:
      name: "${name} temperature sensors"
    charging_cycles:
      id: charging_cycles
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      id: total_charging_cycle_capacity
      name: "${name} total charging cycle capacity"
    battery_strings:
      id: battery_strings 
      name: "${name} battery strings"
    errors_bitmask:
      id: errors_bitmask
      name: "${name} errors bitmask"
    operation_mode_bitmask:
      name: "${name} operation mode bitmask"
    total_voltage_overvoltage_protection:
      name: "${name} total voltage overvoltage protection"
    total_voltage_undervoltage_protection:
      name: "${name} total voltage undervoltage protection"
    cell_voltage_overvoltage_protection:
      name: "${name} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name} cell voltage overvoltage recovery"
    cell_voltage_overvoltage_delay:
      name: "${name} cell voltage overvoltage delay"
    cell_voltage_undervoltage_protection:
      name: "${name} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name} cell voltage undervoltage recovery"
    cell_voltage_undervoltage_delay:
      name: "${name} cell voltage undervoltage delay"
    cell_pressure_difference_protection:
      name: "${name} cell pressure difference protection"
    discharging_overcurrent_protection:
      name: "${name} discharging overcurrent protection"
    discharging_overcurrent_delay:
      name: "${name} discharging overcurrent delay"
    charging_overcurrent_protection:
      name: "${name} charging overcurrent protection"
    charging_overcurrent_delay:
      name: "${name} charging overcurrent delay"
    balance_starting_voltage:
      name: "${name} balance starting voltage"
    balance_opening_pressure_difference:
      name: "${name} balance opening pressure difference"
    power_tube_temperature_protection:
      name: "${name} power tube temperature protection"
    power_tube_temperature_recovery:
      name: "${name} power tube temperature recovery"
    temperature_sensor_temperature_protection:
      name: "${name} temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      name: "${name} temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      name: "${name} temperature sensor temperature difference protection"
    charging_high_temperature_protection:
      name: "${name} charging high temperature protection"
    discharging_high_temperature_protection:
      name: "${name} discharging high temperature protection"
    charging_low_temperature_protection:
      name: "${name} charging low temperature protection"
    charging_low_temperature_recovery:
      name: "${name} charging low temperature recovery"
    discharging_low_temperature_protection:
      name: "${name} discharging low temperature protection"
    discharging_low_temperature_recovery:
      name: "${name} discharging low temperature recovery"
    total_battery_capacity_setting:
      id: total_battery_capacity_setting
      name: "${name} total battery capacity setting"
    current_calibration:
      name: "${name} current calibration"
    device_address:
      name: "${name} device address"
    sleep_wait_time:
      name: "${name} sleep wait time"
    alarm_low_volume:
      name: "${name} alarm low volume"
    manufacturing_date:
      name: "${name} manufacturing date"
    total_runtime:
      name: "${name} total runtime"
    # start_current_calibration:
    #   name: "${name} start current calibration"
    actual_battery_capacity:
      name: "${name} actual battery capacity"
    # protocol_version:
    #   name: "${name} protocol version"

# 3. Define all the available numeric sensors

  - platform: luxpower_sna    
    luxpower_sna_id: ${name}_luxpower_hub
    pv1_voltage:
      name: "${name}_PV1 Voltage"
    pv2_voltage:
      name: "${name}_PV2 Voltage"
    battery_voltage:
      name: "${name}_Battery Voltage"
    soc:
      name: "${name}_Battery SOC"
    pv1_power:
      name: "${name}_PV1 Power"
    pv2_power:
      name: "${name}_PV2 Power"
    charge_power:
      name: "${name}_Battery Charge Power"
    discharge_power:
      name: "${name}_Battery Discharge Power"
    inverter_power:
      name: "${name}_Inverter Power"
    power_to_grid:
      name: "${name}_Power to Grid"
    power_from_grid:
      name: "${name}_Power from Grid"
    grid_voltage_r:
      name: "${name}_Grid Voltage R"
    grid_frequency:
      name: "Grid Frequency"
    #eps_active_power:
    #  name: "EPS Power"
    #bus1_voltage:
    #  name: "Bus1 Voltage"

    # --- Daily Energy Totals ---
    pv1_energy_today:
      name: "${name}_PV1 Energy Today"
    pv2_energy_today:
      name: "${name}_PV2 Energy Today"
    battery_current:
      name: "${name}_Battery Current"
    #battery_count:
    #  name: "Battery Count"
    battery_capacity:
      name: "${name}_Battery Capacity"
    max_cell_voltage:
      name: "${name}_Max Cell Voltage"
    min_cell_voltage:
      name: "${name}_Min Cell Voltage"
